### ISSUE TITLE
API ?

### ISSUE THREAD

**Issue by spinnaker1** [rayanfer32/TgindexPro#15]
Does the API work?

When I try `http://mydomain.com:8080/qMqVTrDyMoGCaX/api/` it does not work, using Postman with GET. I choose the channel, and append an `/api` to the url. Correct?

**Comment by pseudokawaii** [comment]
@spinnaker1 no, all the endpoints mentioned in the API docs are relative to the base URL and when I say base URL, it means `http://mydomain.com` or if you are hosting the code on repl.it, `http://repl-name.username.repl.co` so a proper API request URL would be `http://mydomain.com/api` or `http://repl-name.username.repl.co/api`.

But i'm pretty sure that the API isn't implemented to work with the new code yet.

**Comment by rayanfer32** [comment]
API's are broken as of now.

**Comment by spinnaker1** [comment]
> API's are broken as of now.

Can you reimplement it? It's a very useful feature!

**Comment by rayanfer32** [comment]
Not sure... I dont understand the core server
