### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by VasuDevbyte** [rayanfer32/TgindexPro#17]
What's This🥲
![Screenshot_20210703_162636](https://user-images.githubusercontent.com/81460710/124352106-ea6a6100-dc1b-11eb-9958-51673d1eba2c.jpg)

**Comment by rayanfer32** [comment]
Send the error log

**Comment by VasuDevbyte** [comment]
At first I had bluff erorr then I added Double quotes to my string then got this
![Screenshot_20210703_172839](https://user-images.githubusercontent.com/81460710/124353532-acbe0600-dc24-11eb-8bd7-3f6040c6ccdd.jpg)

**Comment by pseudokawaii** [comment]
@VasuDevbyte don't add quotes while adding the environment variables on the sidebar. And generate the session string again using the internal session string generator tool, command ~

`python app/generate_session_string.py`

**Comment by VasuDevbyte** [comment]
Cmd gone wrng I think my mistake only...
But can I use telethon string by erichsrepl.it externally

**Comment by VasuDevbyte** [comment]
And Zeet Supports This?
