### ISSUE TITLE
Sort the files in ascending order

### ISSUE THREAD

**Issue by sherlockia2** [rayanfer32/TgindexPro#18]
Is it possible to sort the files in ascending order. (From 1st message to the last)
This will be really helpful for channels with TV shows.

**Comment by rayanfer32** [comment]
Yes by default its sorted in the order of message id

**Comment by sherlockia2** [comment]
Currently its showing reverse
![image](https://user-images.githubusercontent.com/74177321/125913507-6bc5be51-5849-43b7-87a9-2c4d24c4a7ba.png)

**Comment by rayanfer32** [comment]
Yes the latest messages are first

**Comment by sherlockia2** [comment]
So is there any way to show the oldest messages first?

**Comment by rayanfer32** [comment]
No ..its not implemented
