### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by winkxx** [Rayanfer32/TgindexPro#2]
I cannot run the project in repl.it，I hope to get help

**Comment by Rayanfer32** [comment]
> I cannot run the project in repl.it，I hope to get help

Send the error you are getting.

**Comment by Rayanfer32** [comment]
> I cannot run the project in repl.it，I hope to get help

I fixed the deploy button , Check now!

**Comment by winkxx** [comment]
> > 我无法在项目中运行该项目。希望获得帮助
> 
> 我固定了部署按钮，现在检查！

Error reported in repl.it
![5ad8fdd1d4776dbfc2d19fd77e7c367](https://user-images.githubusercontent.com/68945988/102686521-3545fd80-4223-11eb-999f-3b00b6da5fda.png)

**Comment by Rayanfer32** [comment]
Yea i fixed the deploy button now

**Comment by Rayanfer32** [comment]
> > > 我无法在项目中运行该项目。希望获得帮助
> > 
> > 
> > 我固定了部署按钮，现在检查！
> 
> Error reported in repl.it
> ![5ad8fdd1d4776dbfc2d19fd77e7c367](https://user-images.githubusercontent.com/68945988/102686521-3545fd80-4223-11eb-999f-3b00b6da5fda.png)

Your session string is incorrect

**Comment by Rayanfer32** [comment]
> > > > 我无法在项目中运行该项目。希望获得帮助
> > > 
> > > 
> > > 我固定了部署按钮，现在检查！
> > 
> > 
> > Error reported in repl.it
> > ![5ad8fdd1d4776dbfc2d19fd77e7c367](https://user-images.githubusercontent.com/68945988/102686521-3545fd80-4223-11eb-999f-3b00b6da5fda.png)
> 
> Your session string is incorrect

Wrap your session string with quotes
