### ISSUE TITLE
How to Deploy Hosting Godaddy or Cloud Flare / Workers 

### ISSUE THREAD

**Issue by thopDB** [Rayanfer32/TgindexPro#30]
Dear Sir 

How to Deploy TG Index in Hosting Servers or Cloudflare / workers. I find out Demo Site Tg Index in Cloud Flare hosted 

Url : https://tg.prabha.tk/0rJ12AcMMH7KA0

I like above TG Index i Kindly request you reply me

**Comment by rayanfer32** [comment]
@thopDB Basically you will need a python supported Linux/windows machine , and cloud flare workers do-not support python

**Comment by thopDB** [comment]
https://tg.prabha.tk/0rJ12AcMMH7KA0
above url where Deploy plz tel me

**Comment by rayanfer32** [comment]
its probably deployed on a vps like linode or aws
