### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by scriptcuddle** [Rayanfer32/TgindexPro#34]
how to fix this bro 
i used this repo https://github.com/rayanfer32/tg-index

![tg-index](https://telegra.ph/file/12577984102b8318ca569.png)

**Comment by pseudokawaii** [comment]
try installing the Pillow module manually using the repl packager.

**Comment by scriptcuddle** [comment]
still error, I'm really confused why this happened

**Comment by rayanfer32** [comment]
Repl.it has broken its dependency tree

**Comment by pseudokawaii** [comment]
> Repl.it has broken its dependency tree

still working for me tho. Just needed a few adjustments.

**Comment by pseudokawaii** [comment]
> still error, I'm really confused why this happened

Try forking this repl -
https://replit.com/@culturecloud/tgdex

No need to modify anything. Just add the three required variables as repl secrets, `API_ID`, `API_HASH` & `INDEX_SETTINGS`. Add `SESSION_STRING` too if you already have one or leave it if you don't. Just run the repl and it will guide you through the process automatically.

**Comment by scriptcuddle** [comment]
> > still error, I'm really confused why this happened
> 
> Try forking this repl - https://replit.com/@culturecloud/tgdex
> 
> No need to modify anything. Just add the three required variables as repl secrets, `API_ID`, `API_HASH` & `INDEX_SETTINGS`. Add `SESSION_STRING` too if you already have one or leave it if you don't. Just run the repl and it will guide you through the process automatically.

thankyou bro this is worked

**Comment by rayanfer32** [comment]
Yep, forking is the only way to get repl working because the newer versions of bash and python repls have broken the dependencies required for the project.

**Comment by pseudokawaii** [comment]
> Yep, forking is the only way to get repl working because the newer versions of bash and python repls have broken the dependencies required for the project.

It works even if you import from github. I imported it from Github first, here's my modified repo ~
https://github.com/culturecloud/tgdex
