### ISSUE TITLE
Please Help to Run

### ISSUE THREAD

**Issue by NEOIR** [Rayanfer32/TgindexPro#7]
Hi

When I Get Code in Telegram and Insert to app 
Show Blow Error
Please Help For Deployment.
![TGIndex Problem](https://user-images.githubusercontent.com/53754407/110213647-1d8f2480-7eb6-11eb-8a7e-77737cd4cf46.jpg)

**Comment by Rayanfer32** [comment]
You cant leave session string empty... It will break the setup.

**Comment by NEOIR** [comment]
Thanks For Resopnse

But, When I Put session string Cause These Error
![TGIndex Problem With Session](https://user-images.githubusercontent.com/53754407/110213957-99d63780-7eb7-11eb-9642-3d7165586a94.jpg)

**Comment by Rayanfer32** [comment]
Insert -100 infront of the INDEXING_CHAT

**Comment by NEOIR** [comment]
Thank You For Support and Response and One More Request to Close This Issue.

## Please Add Login Page for See Content for More Safety.

# Thanks

**Comment by Rayanfer32** [comment]
> Thank You For Support and Response and One More Request to Close This Issue.
> 
> ## Please Add Login Page for See Content for More Safety.
> # Thanks

Feel free to implement it... and send me a pull request !
