### ISSUE TITLE
I can't generate session string 

### ISSUE THREAD

**Issue by LuK03619** [Rayanfer32/TgindexPro#8]
Every time I try to generate session string it gave me the error

Traceback (most recent call last):
File "app/generate_session_string.py", line 12, in
api_id = os.environ['API_ID']#int(input("Enter your API_ID: "))
File "/usr/lib/python3.8/os.py", line 675, in getitem
raise KeyError(key) from None
KeyError: 'API_ID'

But all the keys are not blank

**Comment by H4CK3R-5M4CK3R** [comment]
try to download that script and then run that in your own own pc not in online server and replace os.environ['API_ID'] with your Api id as a number and os.environ['API_HASH'] as api hash as a string

**Comment by H4CK3R-5M4CK3R** [comment]
> Every time I try to generate session string it gave me the error
> 
> Traceback (most recent call last):
> File "app/generate_session_string.py", line 12, in
> api_id = os.environ['API_ID']#int(input("Enter your API_ID: "))
> File "/usr/lib/python3.8/os.py", line 675, in getitem
> raise KeyError(key) from None
> KeyError: 'API_ID'
> 
> But all the keys are not blank

try to download that script and then run that in your own own pc not in online server and replace os.environ['API_ID'] with your Api id as a number and os.environ['API_HASH'] as api hash as a string

**Comment by LuK03619** [comment]
I fixed changing the values in generate_session_string.py, as you told me, and also in config.py.
In chrome it doesn't work with 0.0.0.0:8080 but using localhost:8080 it works pretty well.
Thanks a lot and have a good day.
