### ISSUE TITLE
error

### ISSUE THREAD

**Issue by irabro1992** [Rayanfer32/TgindexPro#9]
hi  , i am getting this error code. any idea to reslove ?

File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/TgindexPro/app/__main__.py", line 19, in <module>
    Indexer().run()
  File "/home/runner/TgindexPro/app/main.py", line 25, in __init__
    self.tg_client = Client(session_string, api_id, api_hash)
  File "/home/runner/TgindexPro/app/telegram.py", line 11, in __init__
    super().__init__(StringSession(session_string), *args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/sessions/string.py", line 37, in __init__
    self._dc_id, ip, self._port, key = struct.unpack(
struct.error: unpack requires a buffer of 275 bytes
exit status 1

**Comment by Rayanfer32** [comment]
Wrap session string with double quotes.

**Comment by irabro1992** [comment]
already did that. it showing me this

**kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/telethon/sessions/string.py", line 33, in __init__
    raise ValueError('Not a valid string')
ValueError: Not a valid string

**Comment by Rayanfer32** [comment]
Plz see the format in .env file in the folder

**Comment by irabro1992** [comment]
https://user-images.githubusercontent.com/73217997/115665961-f4452d80-a369-11eb-9b46-54824c8fee03.png

i did that. but still error.

**Comment by Rayanfer32** [comment]
show me your env file

**Comment by Rayanfer32** [comment]
hardcode session string into the config.py file

**Comment by Rayanfer32** [comment]
If it fixed your issue then please close the issue. :+1:

**Comment by Rayanfer32** [comment]
I see that you havent generated your session string.

**Comment by irabro1992** [comment]
i replaced with my own api id & api id hash. got this error. any tip? sorry for the question :(

Traceback (most recent call last):
  File "D:\Love and Redemption\TgindexPro-main\TgindexPro-main\app\config.py", line 16, in <module>
    api_id = int(os.environ["5441863"])
  File "C:\Python39\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: '5441863'

**Comment by Rayanfer32** [comment]
> i replaced with my own api id & api id hash. got this error. any tip? sorry for the question :(
> 
> Traceback (most recent call last):
> File "D:\Love and Redemption\TgindexPro-main\TgindexPro-main\app\config.py", line 16, in
> api_id = int(os.environ["5441863"])
> File "C:\Python39\lib\os.py", line 679, in **getitem**
> raise KeyError(key) from None
> KeyError: '5441863'

I wouldnt suggest you to modifing the api_id directly in config... you should use the env in repl

**Comment by Rayanfer32** [comment]
**You can re deploy the project using the `run in repl` button in readme**

**Comment by irabro1992** [comment]
![image](https://user-images.githubusercontent.com/73217997/116384488-e72eaf80-a83d-11eb-831e-10f974ca3684.png)

hi , i finished installation. how can i find url to my telegram index ?
now , i am stuck here.

**Comment by Rayanfer32** [comment]
you need to place your generated session string in the environment variable . and comment the first line `run` file

**Comment by Rayanfer32** [comment]
> finally , it working now ^_^ thanks mate.
> by the way , last thing to ask , download bandwidth come from telegram server or replit ?

Actually telegram bandwidth depends on the DC the file is stored  on. Repl.it may throttle the download speed ... but imo repl.it is not capping telegram bandwidth right now.
